//! SQLite integration and versioned migrations.
pub mod attachment_store;
pub mod attributes;
pub mod bins;
pub mod bom;
pub mod build;
pub mod categories;
pub mod dashboard;
mod database;
pub mod dev_seed;
pub mod dimensions;
pub mod enrichment;
pub mod history;
pub mod identity;
pub mod import_commit;
pub mod import_match;
pub mod import_review;
pub mod imports;
pub mod ledger;
pub mod matching;
pub mod parts;
pub mod projects;
pub mod search;
pub mod seed;
pub mod settings;
pub mod validate;
pub use database::{Database, DbError, MIGRATIONS, MISC_CATEGORY_ID, SUPPORTED_SCHEMA_VERSION};
